#!/bin/sh

pxDir=$(pwd)
while [[ "${pxDir}" != "" && ! -e "${pxDir}/px" ]]; do
  pxDir=${pxDir%/*}
done

if [[ -e "${pxDir}/px" ]]; then
  /usr/bin/env python3 "${pxDir}/px" "$@"
else
  echo "ERROR: no px script found in any parent directory"
  exit 1
fi
