name: Deploy documentation

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  build:
    name: Deploy documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build docs
        run: ./pw --clean generate-docs

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: pyprojectx/pyprojectx.github.io
          branch: main
          folder: docs/site
          ssh-key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
